language: python
python:
  - 2.7
  - 3.3
env:
  - BCRYPT=0
  - BCRYPT=1
  - SCRYPT=0
  - SCRYPT=1
install:
  - pip install --use-mirrors -r requirements.txt
  - "if [[ $BCRYPT == 1 ]]; then pip install py-bcrypt; fi"
  - "if [[ $SCRYPT == 1 ]]; then pip install -e hg+https://bitbucket.org/mhallin/py-scrypt#egg=scrypt; fi"
  - python setup.py check --metadata --strict
  - pip install .
script:
  - py.test -v
  - sphinx-build -aEWb linkcheck docs docs/_build
  - sphinx-build -aEWb doctest docs docs/_build
