language: python
python:
  - 2.7
  - 3.3
env:
  - BCRYPT=0
  - BCRYPT=1
install:
  - pip install --use-mirrors -r requirements.txt
  - "if [[ $BCRYPT == 1 ]]; then pip install py-bcrypt; fi"
  - pip install .
script: py.test
